### ISSUE TITLE
[feature/rewrite-app] Notifications not show in windows

### ISSUE THREAD

**Issue by mauri870** [devfake/cloudradioo-app#1]
The app notifications not show in windows.

In the `node-notifier` error callback the following message is returning:

```
Error: spawn C:\vendor\toaster\toast.exe ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I think it is related to the issue in [#117](https://github.com/mikaelbr/node-notifier/issues/117) on node-notifier

**Comment by mauri870** [comment]
I try to copy the build folder from my linux machine (where the notifications work) to my windows machine and the same problem occur..

Seems like to fallback to Electron Web API for notifications :(

**Comment by mauri870** [comment]
Well, I find the solution
Webpack need the following config:

```
  node: {
    __filename: true,
    __dirname: true
  },
```
